# Generated by Django 5.2.7 on 2025-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(null=True, verbose_name='头像'),
        ),
    ]
