# Generated by Django 5.2.7 on 2025-12-08 04:13

from decimal import Decimal
from django.db import migrations



def create_default_membership_types(apps, schema_editor):
    MembershipType = apps.get_model('accounts', 'MembershipType') 
    db_alias = schema_editor.connection.alias
    defaults = [
        {
            'name': 'Monthly',
            'description': '1个月会员',
            'price': Decimal('29.90'),
            'duration_days': 30,

        },
        {

            'name': 'HalfYear',
            'description': '6个月会员',
            'price': Decimal('149.00'),
            'duration_days': 180,
        },
        {
            'name': 'Annual',
            'description': '1年会员',
            'price': Decimal('249.00'),
            'duration_days': 365,
        },
    ]


    for item in defaults:
        MembershipType.objects.using(db_alias).get_or_create(
            name=item['name'],
            defaults=item
        )


def reverse_create_default_membership_types(apps, schema_editor):
    MembershipType = apps.get_model('accounts', 'MembershipType')
    db_alias = schema_editor.connection.alias
    MembershipType.objects.using(db_alias).filter(name__in=['Monthly', 'HalfYear', 'Annual']).delete()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membershiptype_subscription'),
    ]
    operations = [
        migrations.RunPython(create_default_membership_types, reverse_create_default_membership_types),
    ]