"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # 设置默认值和类型提示（可选但推荐）
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list,[]),
    CORS_ALLOWED_ORIGINS=(list,[]),
    ALIPAY_DEBUG=(bool, False),
)


if os.getenv("DJANGO_ENV") != "production":
    environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS", default=['testserver'])
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'django_redis',
    'corsheaders',


    'courses.apps.CoursesConfig',
    'accounts.apps.AccountsConfig',
    'commerce.apps.CommerceConfig',
    'file_management.apps.FileManagementConfig',
    'performance.apps.PerformanceConfig',
]
#judge
JUDGE0_BASE_URL= env("JUDGE0_BASE_URL")
JUDGE0_API_KEY= env("JUDGE0_API_KEY")
# DRF 全局设置 (可选，但推荐)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [

        'rest_framework_simplejwt.authentication.JWTAuthentication',   # 允许基于 JWT Auth
        'rest_framework.authentication.SessionAuthentication', # 允许基于会话的认证
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # 默认只允许认证用户访问
        #'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'courses.pagination.CustomPageNumberPagination',
    'PAGE_SIZE': 10, # 默认每页10条数据
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer', # 方便在浏览器中调试API
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}
# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=1,minutes=1000000),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,  # Auto-revoke old refresh token
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.logging_middleware.LoggingMiddleware',  # 日志中间件
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {"default": env.db()}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password hashing
# Use Argon2 as the preferred password hasher for new passwords
# PBKDF2 is kept for backward compatibility with existing password hashes
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Preferred for new passwords
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',  # Fallback for existing hashes
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# 静态文件收集目录（必须是绝对路径）
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Media files (user uploads) - defaults to local storage
MEDIA_ROOT = env('MEDIA_PATH',default=os.path.join(BASE_DIR, 'media'))
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Session configuration to use Redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# 支付宝
ALIPAY_APPID = env('ALIPAY_APPID')
ALIPAY_PRIVATE_KEY_PATH = env('ALIPAY_PRIVATE_KEY_PATH')
ALIPAY_PUBLIC_KEY_PATH = env('ALIPAY_PUBLIC_KEY_PATH')
ALIPAY_NOTIFY_URL = env('ALIPAY_NOTIFY_URL')
ALIPAY_RETURN_URL = env('ALIPAY_RETURN_URL')
ALIPAY_DEBUG = env('ALIPAY_DEBUG')


# File storage settings
# S3 settings
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default='')
AWS_DEFAULT_ACL = env('AWS_DEFAULT_ACL', default='public-read')
AWS_S3_USE_SSL = env('AWS_S3_USE_SSL', default=True)
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_LOCATION = env('AWS_LOCATION', default='media')
AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL', default=None)

# MinIO settings (S3 compatible)
MINIO_ENDPOINT_URL = env('MINIO_ENDPOINT_URL', default='http://localhost:9000')
MINIO_ACCESS_KEY = env('MINIO_ACCESS_KEY', default='')
MINIO_SECRET_KEY = env('MINIO_SECRET_KEY', default='')
MINIO_BUCKET_NAME = env('MINIO_BUCKET_NAME', default='file-management')
MINIO_REGION_NAME = env('MINIO_REGION_NAME', default='')
MINIO_USE_SSL = env('MINIO_USE_SSL', default=False)
MINIO_VERIFY = env('MINIO_VERIFY', default=True)


# File upload settings
# 保守策略：仅允许文档类文件
ALLOWED_FILE_EXTENSIONS = [
    '.txt', '.md', '.pdf',           # 文档
    '.doc', '.docx',                 # Word 文档
    '.ppt', '.pptx',                 # PowerPoint
    '.csv', '.json', '.xml',         # 数据文件
    '.ipynb', '.py',                 # Jupyter Notebook 和 Python 源码
]
MAX_UPLOAD_FILE_SIZE = 100 * 1024 * 1024  # 100MB per file
MAX_USER_STORAGE_QUOTA = 5 * 1024 * 1024 * 1024  # 5GB per user





### Celery配置
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND',default="redis://localhost:6379/2")
CELERY_BROKER_URL = env('CELERY_BROKER_URL',default="redis://localhost:6379/3")
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = True
CELERY_RESULT_EXTENDED = True  # 启用后才会记录 task_name、date_started 等字段
CELERY_TASK_TRACK_STARTED = True  # 记录任务开始时间

#CORS配置
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_HEADERS = ('authorization','content-type')


# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'detailed': {
            '()': 'common.utils.logging.DetailedFormatter',
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),
            'maxBytes': 1024*1024*10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'api_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/api.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 10,
            'formatter': 'json' if not DEBUG else 'detailed',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/error.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 10,
            'formatter': 'json' if not DEBUG else 'verbose',
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/security.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 10,
            'formatter': 'json',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/celery.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'teaching_platform': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'teaching_platform.api': {
            'handlers': ['api_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'teaching_platform.security': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'teaching_platform.performance': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'teaching_platform.models': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'teaching_platform.database': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}