# Generated by Django 5.2.7 on 2025-12-12 07:00

import django.db.models.deletion
import file_management.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Original file name')),
                ('file', models.FileField(max_length=500, upload_to=file_management.models.file_upload_path)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_backend', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO')], default='local', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Allow public access to the file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Entry',
                'verbose_name_plural': 'File Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
