# Generated by Django 5.2.7 on 2025-12-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Original file name'),
        ),
        migrations.AlterField(
            model_name='fileentry',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('minio', 'MinIO (S3 Compatible)')], default='local', max_length=20),
        ),
    ]
