# Generated by Django 5.2.7 on 2025-12-15 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_alter_fileentry_name_alter_fileentry_storage_backend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Original file name'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Folder name')),
                ('is_public', models.BooleanField(default=False, help_text='Allow public access to the folder and its contents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_management.folder', verbose_name='Parent folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'parent', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='fileentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_management.folder', verbose_name='Parent folder'),
        ),
        migrations.AlterUniqueTogether(
            name='fileentry',
            unique_together={('name', 'folder', 'owner')},
        ),
    ]
