# Generated by Django 5.2.7 on 2026-01-06 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_alter_fileentry_name_folder_fileentry_folder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['owner'], name='file_manage_owner_i_2363ea_idx'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['folder'], name='file_manage_folder__bc7cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['owner', 'folder'], name='file_manage_owner_i_187a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['created_at'], name='file_manage_created_c3431a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['name', 'folder'], name='file_manage_name_23d772_idx'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['is_public'], name='file_manage_is_publ_1dc294_idx'),
        ),
        migrations.AddIndex(
            model_name='fileentry',
            index=models.Index(fields=['owner', 'is_public'], name='file_manage_owner_i_d2c71d_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner'], name='file_manage_owner_i_30a304_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='file_manage_parent__5819f5_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='file_manage_owner_i_7956ed_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_at'], name='file_manage_created_e06ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name', 'parent'], name='file_manage_name_bf0e7f_idx'),
        ),
    ]
