# Generated by Django 5.2.7 on 2026-01-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_management.folder', verbose_name='Parent folder'),
        ),
    ]
