# Generated by Django 5.2.7 on 2025-12-08 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_membershiptype_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('failed', '支付失败')], default='pending', max_length=20, verbose_name='订单状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='支付流水号')),
                ('membership_type', models.ForeignKey(blank=True, help_text='仅用于会员订阅类订单', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.membershiptype')),
                ('subscription', models.OneToOneField(blank=True, help_text='支付成功后创建的订阅', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
