# Generated by Django 5.2.7 on 2025-10-22 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('content', models.TextField(blank=True, verbose_name='章节内容')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='章节顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('algorithm', '算法题')], db_index=True, max_length=20, verbose_name='问题类型')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('difficulty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='难度等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='courses.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题列表',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.PositiveSmallIntegerField(default=1000, help_text='毫秒', verbose_name='时间限制（毫秒）')),
                ('memory_limit', models.PositiveSmallIntegerField(default=256, help_text='MB', verbose_name='内存限制（MB）')),
                ('code_template', models.JSONField(blank=True, null=True, verbose_name='编码模板')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_info', to='courses.problem', verbose_name='关联问题主表')),
            ],
            options={
                'verbose_name': '算法题',
                'verbose_name_plural': '算法题列表',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='提交的代码')),
                ('language', models.CharField(default='python', max_length=50, verbose_name='编程语言')),
                ('status', models.CharField(choices=[('pending', '待评测'), ('judging', '评测中'), ('accepted', '通过'), ('wrong_answer', '答案错误'), ('time_limit_exceeded', '超时'), ('memory_limit_exceeded', '内存超限'), ('runtime_error', '运行时错误'), ('compilation_error', '编译错误'), ('internal_error', '系统错误')], default='pending', max_length=30, verbose_name='评测状态')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(毫秒)')),
                ('memory_used', models.FloatField(blank=True, null=True, verbose_name='内存使用(KB)')),
                ('output', models.TextField(blank=True, verbose_name='程序输出')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.problem', verbose_name='提交的问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='输入数据')),
                ('expected_output', models.TextField(verbose_name='预期输出')),
                ('is_sample', models.BooleanField(default=False, verbose_name='是否为示例测试用例')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='courses.algorithmproblem', verbose_name='所属问题')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
    ]
