# Generated by Django 5.2.7 on 2025-11-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_discussionthread_discussionreply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionthread',
            options={'ordering': ['-is_pinned', '-last_activity_at'], 'verbose_name': '主题贴', 'verbose_name_plural': '主题贴'},
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_discussion_threads', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_discussion_threads', to='courses.problem'),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='courses.course'),
        ),
    ]
