# Generated by Django 5.2.7 on 2025-11-07 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_discussionthread_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionthread',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='courses.problem'),
        ),
    ]
