# Generated by Django 5.2.7 on 2025-12-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_discussionthread_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemUnlockCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_date', models.DateTimeField(blank=True, help_text='在此日期之前题目将被锁定', null=True, verbose_name='解锁日期')),
                ('unlock_condition_type', models.CharField(choices=[('prerequisite', '前置题目'), ('date', '解锁日期'), ('both', '前置题目和解锁日期'), ('none', '无条件')], default='none', max_length=20, verbose_name='解锁条件类型')),
                ('minimum_percentage', models.PositiveSmallIntegerField(blank=True, help_text='用户需要完成前置题目中的百分比才能解锁当前题目', null=True, verbose_name='最低完成百分比')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prerequisite_problems', models.ManyToManyField(blank=True, help_text='必须完成这些前置题目才能解锁当前题目', related_name='dependent_problems', to='courses.problem', verbose_name='前置题目')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_condition', to='courses.problem', verbose_name='解锁条件关联的问题')),
            ],
            options={
                'verbose_name': '题目解锁条件',
                'verbose_name_plural': '题目解锁条件',
            },
        ),
    ]
