# Generated by Django 5.2.7 on 2026-01-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_problemunlockcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemunlockcondition',
            name='minimum_percentage',
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('algorithm', '算法题'), ('choice', '选择题'), ('fillblank', '填空题')], db_index=True, max_length=20, verbose_name='问题类型'),
        ),
        migrations.CreateModel(
            name='FillBlankProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_with_blanks', models.TextField(help_text='使用 [blank1], [blank2] 等标记空白位置', verbose_name='带空白的内容')),
                ('blanks', models.JSONField(help_text="格式1（详细）: {'blank1': {'answer': ['答案1', '备选'], 'case_sensitive': False}, 'blank2': {'answer': ['答案2'], 'case_sensitive': True}}. 格式2（简单）: {'blanks': ['答案1', '答案2'], 'case_sensitive': False}. 格式3（推荐）: {'blanks': [{'answers': ['答案1', '备选1'], 'case_sensitive': False}, {'answers': ['答案2'], 'case_sensitive': True}]}", verbose_name='空白答案配置')),
                ('blank_count', models.PositiveSmallIntegerField(default=1, verbose_name='空白数量')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fillblank_info', to='courses.problem', verbose_name='关联问题主表')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题列表',
            },
        ),
    ]
