# Generated by Django 5.2.7 on 2026-01-12 07:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_problemunlockcondition_minimum_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='测验标题')),
                ('description', models.TextField(blank=True, verbose_name='测验描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='0表示不限制，以结束时间为准', verbose_name='答题时长(分钟)')),
                ('total_score', models.PositiveIntegerField(default=100, help_text='由系统根据题目分数自动计算', verbose_name='总分')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name='及格分数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='是否随机排序题目')),
                ('show_results_after_submit', models.BooleanField(default=True, verbose_name='提交后立即显示结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '测验',
                'verbose_name_plural': '测验列表',
                'ordering': ['course', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='题目分值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='题目顺序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必答')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_problems', to='courses.exam', verbose_name='所属测验')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_problems', to='courses.problem', verbose_name='关联题目')),
            ],
            options={
                'verbose_name': '测验题目',
                'verbose_name_plural': '测验题目列表',
                'ordering': ['exam', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('submitted', '已提交'), ('auto_submitted', '自动提交(超时)'), ('graded', '已评分')], default='in_progress', max_length=20, verbose_name='状态')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='总分')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='是否及格')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='用时(秒)')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='courses.enrollment', verbose_name='课程注册记录')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.exam', verbose_name='所属测验')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '测验提交',
                'verbose_name_plural': '测验提交记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_answers', models.JSONField(blank=True, null=True, verbose_name='选择题答案')),
                ('fillblank_answers', models.JSONField(blank=True, null=True, verbose_name='填空题答案')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='得分')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('correct_percentage', models.FloatField(blank=True, null=True, verbose_name='正确比例（用于填空题）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='courses.problem', verbose_name='题目')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.examsubmission', verbose_name='所属提交')),
            ],
            options={
                'verbose_name': '测验答案',
                'verbose_name_plural': '测验答案详情',
                'ordering': ['submission', 'problem__id'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'status'], name='courses_exa_course__2b361b_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time', 'end_time'], name='courses_exa_start_t_063ffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examproblem',
            unique_together={('exam', 'problem')},
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['exam', 'user'], name='courses_exa_exam_id_294cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['status', '-started_at'], name='courses_exa_status_0bbd7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('exam', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('submission', 'problem')},
        ),
    ]
