# Generated by Django 5.2.7 on 2026-01-22 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_exam_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examproblem',
            unique_together={('exam', 'problem', 'order')},
        ),
        migrations.CreateModel(
            name='CodeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='代码内容')),
                ('language', models.CharField(default='python', max_length=50, verbose_name='编程语言')),
                ('save_type', models.CharField(choices=[('auto_save', '自动保存'), ('manual_save', '手动保存'), ('submission', '提交记录')], db_index=True, default='auto_save', max_length=20, verbose_name='保存类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('problem', models.ForeignKey(limit_choices_to={'type': 'algorithm'}, on_delete=django.db.models.deletion.CASCADE, related_name='code_drafts', to='courses.problem', verbose_name='问题')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_drafts', to='courses.submission', verbose_name='关联提交记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_drafts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '代码草稿',
                'verbose_name_plural': '代码草稿历史',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'problem', '-created_at'], name='courses_cod_user_id_5cac71_idx'), models.Index(fields=['user', 'problem', 'save_type'], name='courses_cod_user_id_ab7767_idx')],
            },
        ),
    ]
