# Generated by Django 5.2.7 on 2026-01-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_examproblem_unique_together_codedraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterUnlockCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_date', models.DateTimeField(blank=True, help_text='在此日期之前章节将被锁定', null=True, verbose_name='解锁日期')),
                ('unlock_condition_type', models.CharField(choices=[('prerequisite', '前置章节'), ('date', '时间解锁'), ('all', '全部条件')], default='all', max_length=20, verbose_name='解锁条件类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_condition', to='courses.chapter', verbose_name='解锁条件关联的章节')),
                ('prerequisite_chapters', models.ManyToManyField(blank=True, help_text='必须完成这些前置章节才能解锁当前章节', related_name='dependent_chapters', to='courses.chapter', verbose_name='前置章节')),
            ],
            options={
                'verbose_name': '章节解锁条件',
                'verbose_name_plural': '章节解锁条件',
            },
        ),
    ]
