# Generated by Django 5.2.7 on 2026-02-23 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_chapterunlockcondition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examsubmission',
            name='courses_exa_exam_id_294cbc_idx',
        ),
        migrations.AlterField(
            model_name='chapterprogress',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='chapterunlockcondition',
            name='unlock_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='在此日期之前章节将被锁定', null=True, verbose_name='解锁日期'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='课程标题'),
        ),
        migrations.AlterField(
            model_name='problemprogress',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('solved', '已解决'), ('failed', '失败')], db_index=True, default='not_started', max_length=20, verbose_name='解决状态'),
        ),
        migrations.AddIndex(
            model_name='chapterprogress',
            index=models.Index(fields=['enrollment', 'completed'], name='courses_cha_enrollm_11d46a_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['type', '-created_at', 'id'], name='courses_pro_type_f6e389_idx'),
        ),
        migrations.AddIndex(
            model_name='problemprogress',
            index=models.Index(fields=['enrollment', 'status'], name='courses_pro_enrollm_a2e1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem', 'status'], name='courses_sub_user_id_96b30b_idx'),
        ),
    ]
