# Generated by Django 5.2.7 on 2026-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_examsubmission_courses_exa_exam_id_294cbc_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chapterprogress',
            index=models.Index(fields=['chapter', 'completed'], name='courses_cha_chapter_f6f712_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterunlockcondition',
            index=models.Index(fields=['chapter', 'unlock_condition_type'], name='courses_cha_chapter_e1b861_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterunlockcondition',
            index=models.Index(fields=['unlock_date'], name='courses_cha_unlock__4de247_idx'),
        ),
    ]
