# Generated by Django 5.2.7 on 2026-02-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_courseunlocksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemUnlockSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unlock_states', models.JSONField(default=dict, help_text='课程所有题目的解锁状态映射', verbose_name='解锁状态')),
                ('computed_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='计算时间')),
                ('is_stale', models.BooleanField(db_index=True, default=False, help_text='标记快照是否需要重新计算', verbose_name='是否过期')),
                ('version', models.PositiveIntegerField(default=1, help_text='快照版本，用于乐观锁和监控', verbose_name='版本号')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_unlock_snapshots', to='courses.course', verbose_name='课程')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_unlock_snapshot', to='courses.enrollment', verbose_name='课程注册记录')),
            ],
            options={
                'verbose_name': '问题解锁状态快照',
                'verbose_name_plural': '问题解锁状态快照',
                'indexes': [models.Index(fields=['course', 'enrollment'], name='courses_pro_course__183e6a_idx'), models.Index(fields=['is_stale', 'computed_at'], name='courses_pro_is_stal_3bfb41_idx'), models.Index(fields=['enrollment'], name='courses_pro_enrollm_2c0270_idx')],
                'unique_together': {('course', 'enrollment')},
            },
        ),
    ]
